checkoutLocation: /

workspaceLocation: /

image:
  file: Dockerfile
  
ports:
  - port: 6080
    protocol: "http"
    
tasks:
  - command: gp await-port 6080                 &&
             xterm -geometry 200x50+0+0         &&
             xterm -geometry 200x50+0+250       &&
             gp preview $(gp url 6080)    
       
       
  - command: "go get -v ./... "
  
  
  
             
  
  # not getting the following working from the .gitpod.yml file, but it works fine from the command line
  # go run /workspace/src/github.com/hpssjellis/gitpod-hello-ui-demo/main.go 
